# Site settings
title: Andrew's Blog # site title
description: >- # site description
  👋 Hey, it's Andrew, and this is my blog
lang: en-US # default lang
timezone: America/Regina # set your timezone
image: assets/img/avatar.png # This image used for Open Graph more info https://ogp.me/ (preview link)
repo: https://github.com/Zeyu-Li/blog # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: 👋 Hey, it's Andrew! # author name
  bio: >- # tell to the world
    Experience technology with me as I journey through uni life! I also do art whenever I get time <br>(usually vector, isometric vector, or 3D). <br> Follow me on <a href="https://github.com/Zeyu-Li" target="_blank" rel="noopener">@github</a> or view my website <a href="https://zeyu-li.github.io/website/" target="_blank" rel="noopener">here</a>.
  username: Andrew # general username
  github: Zeyu-Li # github username
  email: zeyu.li23@gmail.com # email adress
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "https://andrew-li-blog.vercel.app/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - init.sh

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
